baseURL: /
title: Goldydocs
enableRobotsTXT: true
theme:
  - docsy
enableGitInfo: true
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
metaDataFormat: "yaml"
disableKinds:
  - taxonomy
  - taxonomyTerm
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango
permalinks:
  blog: "/:section/:year/:month/:day/:slug/"
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: UA-00000000-0
languages:
  en:
    title: Goldydocs
    description: A Docsy example site
    languageName: English
    weight: 1
  "no":
    title: Goldydocs
    description: Docsy er operativsystem for skyen
    languageName: Norsk
    contentDir: content/no
    time_format_default: 02.01.2006
    time_format_blog: 02.01.2006
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  copyright: The Docsy Authors
  privacy_policy: "https://policies.google.com/privacy"
  version_menu: Releases
  archived_version: false
  version: "0.0"
  url_latest_version: "https://example.com"
  github_repo: "https://github.com/google/docsy-example"
  github_project_repo: "https://github.com/google/docsy"
  gcs_engine_id: "011737558837375720776:fsdu1nryfng"
  algolia_docsearch: false
  offlineSearch: false
  ui:
    sidebar_menu_compact: false
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: true
    footer_about_disable: false
    feedback:
      enable: true
      "yes": >-
        Glad to hear it! Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
      "no": >-
        Sorry to hear that. Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
    readingtime:
      enable: false
  links:
    user:
      - name: User mailing list
        url: "https://example.org/mail"
        icon: fa fa-envelope
        desc: Discussion and help from your fellow users
      - name: Twitter
        url: "https://example.org/twitter"
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
      - name: Stack Overflow
        url: "https://example.org/stack"
        icon: fab fa-stack-overflow
        desc: Practical questions and curated answers
    developer:
      - name: GitHub
        url: "https://github.com/google/docsy"
        icon: fab fa-github
        desc: Development takes place here!
      - name: Slack
        url: "https://example.org/slack"
        icon: fab fa-slack
        desc: Chat with other project developers
      - name: Developer mailing list
        url: "https://example.org/mail"
        icon: fa fa-envelope
        desc: Discuss development issues around the project
